-- AlterTable
ALTER TABLE "Material" ADD COLUMN     "sku" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "weight" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "OrderService" ADD COLUMN     "weight" DOUBLE PRECISION NOT NULL DEFAULT 0;
